---
- name: Ping ISS hosts and show model number
  hosts: ISSDB150
  gather_facts: no
  ignore_unreachable: yes

  tasks:
    - name: Show hardware model number
      ansible.builtin.raw: ls /Status/Hardware-Info/Model-Number
      register: model_cmd

    - name: Output model number
      ansible.builtin.debug:
        msg: "{{ model_cmd.stdout | trim }}"
      when:
        - model_cmd is defined
        - model_cmd.stdout is defined
        - model_cmd.stdout | trim != ""
