---
- name: Ping ISS hosts and show model number
  hosts: ISS
  gather_facts: no
  ignore_unreachable: yes

  tasks:
    - name: Ping host
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes

    - name: Show hardware model number
      ansible.builtin.raw: ls /Status/Hardware-Info/Model-Number
      register: model_cmd
      when: ping_result is succeeded

    - name: Output model number
      ansible.builtin.debug:
        msg: "{{ model_cmd.stdout | trim }}"
      when: model_cmd is defined and model_cmd.rc == 0
